using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ExCubePlayer : MonoBehaviour
{
    public Text TextUI = null;              //ลุฝบฦฎ UI
    public int Count = 0;                   //ธถฟ์ฝบ ลฌธฏ ฤซฟ๎ลอ
    public float Power = 100.0f;            //นฐธฎ ศ๛ ผ๖ฤก
    public Rigidbody m_Rigidbody;           //ฟภบ๊มงฦฎภว ฐญรผ

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space)) //ฝบฦไภฬฝบนูธฆ ดญทถภป ถง
        {
            Count += 1;                                 //ธถฟ์ฝบฐก ลฌธฏตวพ๚ภปถง Countธฆ 1พฟ ฟรธฐดู.
            TextUI.text = Count.ToString();                 //UI ฐปฝล
            Power = Random.Range(100, 200);                 // 100 ~ 200 ป็ภฬภว ฐชภว ศ๛ภป มุดู.
            m_Rigidbody.AddForce(transform.up * Power);     //Yรเภธทฮ ผณมควั ศ๛ภป มุดู.
        }
        
        if(gameObject.transform.position.y >= 2 || gameObject.transform.position.y <= -2)
        {   //ฟภบ๊มงฦฎภว yฐชภฬ -2 ภฬวฯภฬฐลณช 2ภฬป๓ภฯฐๆฟ์ มถฐวนฎ
            TextUI.text = "ฝวฦะ";
            Count = 0;                                  //ฝวฦะฝร ฤซฟ๎ลอ รสฑโศญ
        }
    }
}