using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;                //РЏДЯЦМ UIПЁ СЂБйЧЯБтРЇЧи ЛчПы

public class ExPlayer : MonoBehaviour
{
    public int Hp = 100;
    public Text TextUI = null;

    // Update is called once per frame
    void Update()
    {
        TextUI.text = Hp.ToString();     //UIdpПЁ УМЗТ ЧЅНУ

        if (Input.GetMouseButtonDown(0)) //ИЖПьНК ПоТЪ РдЗТРЬ ЕЧОњРЛ ЖЇ СЖАЧ
        {
            Hp -= 10;                    //Hp = Hp - 10
            if (Hp <= 10)                 //УМЗТРЬ 0РЬЧЯАЁ ЕЧИщ ЦФБЋЕШДй.
            {
                TextUI.text = Hp.ToString();    //UIПЁ УМЗТ ЧЅНУ
                Destroy(gameObject);    //gameObjectДТ НКХЉИГЦЎАЁ КйОюРжДТ ПРКъСЇЦЎИІ СіФЊ
            }
        }
    }
}
